title: Juncture

description: >
  Juncture makes it easy to create interactive, component-rich web pages using simple Markdown.

author:
  name: Ron Snyder
  email: ron@snyderjr.com

github:
  owner_name: juncture-digital
  repository_name: juncture-digital.github.io
  source:
    branch: image-compare-enhancement

collections:
  components:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/

nav_pages:
  - index.md
  - about.md
  - _docs/index.md
  - _examples/index.md
  - blog.md

max-width: 1000px

blog:
  enabled: false
  show_excerpts: true
  show_rss_feed: true

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
